spring:
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-circular-references: false
  jpa:
    hibernate:
      ddl-auto: none
soap:
  client:
    default-uri: ${SOAP_CLIENT_DEFAULT_URI:http://172.17.0.1:7878}
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/acore_auth
      username: root
      password: Wowlibre96@@
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/acore_characters
      username: root
      password: Wowlibre96@@
      driver-class-name: com.mysql.cj.jdbc.Driver
    three:
      url: jdbc:mysql://localhost:3306/acore_world
      username: root
      password: Wowlibre96@@
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
application:
  urls:
    core-base: http://localhost:8091
  security:
    jwt:
      secret-key: A3F1E4B2D0A728C9F54D8B32C7A59A7D0B9A8F94D1F6C762E7DA56231988C158
      expiration: 604800000  # 7 day
      refresh-token:
        expiration: 1209600000 # 14 días
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    primary:
      url: ${DB_WOW_CLIENT_HOST_AUTH}
      username: ${DB_WOW_CLIENT_USERNAME}
      password: ${DB_WOW_CLIENT_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: ${DB_WOW_CLIENT_HOST_CHARACTERS}
      username: ${DB_WOW_CLIENT_USERNAME}
      password: ${DB_WOW_CLIENT_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    three:
      url: ${DB_WOW_CLIENT_HOST_WORLD}
      username: ${DB_WOW_CLIENT_USERNAME}
      password: ${DB_WOW_CLIENT_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: ${WOW_CLIENT_SERVER_PORT}
application:
  urls:
    core-base: ${HOST_BASE_CORE}
  security:
    jwt:
      secret-key: ${WOW_CLIENT_SECRET_JWT}
      expiration: 604800000  # 7 day
      refresh-token:
        expiration: 1209600000 # 14 días
soap:
  client:
    default-uri: ${SOAP_CLIENT_DEFAULT_URI}